apiVersion: v1
kind: Pod
metadata:
  name: hello
  labels:
    app: hello
spec:
  containers:
  - name: hello
    image: przemekmalak/hello
    ports:
    - containerPort: 5000
      name: http
      protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: helloapp
spec:
  selector:
    app: hello
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
    nodePort: 32000