apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: pod
spec:
  volumes:
  - name: vol1
    persistentVolumeClaim:
      claimName: claim
  containers:
  - image: przemekmalak/tools
    args: ["sh", "-c", "sleep infinity"]
    name: pod
    resources: {}
    volumeMounts:
    - name: vol1
      mountPath: /volume
  dnsPolicy: ClusterFirst
status: {}
