kind: Pod
apiVersion: v1
metadata:
  name: myfrontend
  labels:
    app: storage-demo
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/mnt/azure"
        name: volume
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: azure-managed-disk-mifurm-mbank