apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk-mifurm-mbank
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 5Gi