apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: eu-west-1
  version: "1.16"
vpc:
  nat:
    gateway: Disable # other options: Disable, Single (default)
nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    minSize: 1
    maxSize: 1
    desiredCapacity: 1

