apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: scaled
  name: scaled
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scaled
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: scaled
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: 
          requests:
            memory: 250Mi
            cpu: 1000m
          limits:
            memory: 250Mi
            cpu: 1000m
