# An example of ClusterConfig object using Managed Nodes
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: eu-west-1

managedNodeGroups:
  - name: managed-ng
    instanceType: t3.medium
    minSize: 1
    desiredCapacity: 1
    maxSize: 1
    volumeSize: 20
    labels: {role: worker}

