apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: eu-west-1

nodeGroups:
  - name: ng-spots-1
    minSize: 1
    maxSize: 5
    instancesDistribution:
      maxPrice: 1
      instanceTypes: ["t3.medium", "c5.large"] # At least one instance type should be specified
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0
      spotInstancePools: 1
    iam:
      withAddonPolicies:
        autoScaler: true
  - name: ng-spots-2
    minSize: 1
    maxSize: 5
    instancesDistribution:
      maxPrice: 1
      instanceTypes: ["t3.medium", "c5.large"] # At least one instance type should be specified
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0
      spotInstancePools: 1
  - name: ng-1-1-16
    instanceType: t3.medium
    minSize: 1
    maxSize: 7
    availabilityZones: [ "eu-west-1b"]
    desiredCapacity: 1
