apiVersion: v1
kind: Pod
metadata:
  name: env
spec:
  containers:
  - image: alpine
    env:
    - name: INTERVAL
      value: "30"
    - name: FIRST_VAR
      value: foo
    - name: SECOND_VAR
      value: $(FIRST_VAR)bar
    name: env
    command:  [ "/bin/sh", "-c", "env && sleep 3600" ]
