apiVersion: v1
kind: Pod
metadata:
  name: env-from-configmap
spec:
  containers:
  - image: alpine
    name: env
    env:
    - name: INTERVAL
      valueFrom: 
        configMapKeyRef:
          name: configmap
          key: var1
    - name: TEXT
      valueFrom: 
        configMapKeyRef:
          name: configmap
          key: var2
    command:  [ "/bin/sh", "-c", "env && sleep 3600" ]

