apiVersion: v1
kind: Pod
metadata:
  name: env-from-configmap
spec:
  containers:
  - image: alpine
    name: env
    envFrom:
      - configMapRef:
          name: configmap
        prefix: CONFIG_
    command:  [ "/bin/sh", "-c", "env && sleep 3600" ]

