apiVersion: v1
kind: Pod
metadata:
  name: secret
spec:
  containers:
  - image: alpine
    name: secret
    volumeMounts:
    - name: secret-volume
      mountPath: /var/secret
    command:  [ "/bin/sh", "-c", "sleep 3600" ]
  volumes:
  - name: secret-volume
    secret:
      secretName: mysecret