apiVersion: v1
kind: Pod
metadata:
  name: secret
spec:
  containers:
  - image: alpine
    name: secret
    env: 
      - name: MY_SECRET
        valueFrom: 
          secretKeyRef:
            name: mysecret
            key: key1
    command:  [ "/bin/sh", "-c", "sleep 3600" ]
  volumes:
  - name: secret-volume
    secret:
      secretName: mysecret