apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-sa
  namespace: web
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-reader-sa-rolebinding
  namespace: web
subjects:
- kind: ServiceAccount
  name: web-sa
  namespace: web
roleRef:
  kind: Role
  name: pods-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: curl-with-proxy
  namespace: web
spec:
  serviceAccountName: web-sa
  containers:
  - name: main
    image: tutum/curl
    command: ["sleep", "9999999"]
  - name: proxy
    image: przemekmalak/kubectl-proxy