apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-reader-sa
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: node-reader
rules:
- apiGroups: [""]
  verbs: ["get", "list"]
  resources: ["nodes"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nodes-reader-sa-rolebinding
subjects:
- kind: ServiceAccount
  name: node-reader-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: node-reader
  apiGroup: ""
---
apiVersion: v1
kind: Pod
metadata:
  name: curl-with-proxy
spec:
  serviceAccountName: node-reader-sa
  containers:
  - name: main
    image: tutum/curl
    command: ["sleep", "9999999"]
  - name: proxy
    image: przemekmalak/kubectl-proxy