apiVersion: v1
kind: ServiceAccount
metadata:
  name: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug
  labels:
    app: debug
spec:
  selector:
    matchLabels:
      app: vault
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-dbcreds: "database/creds/readonly"
        vault.hashicorp.com/role: "myapp"
      labels:
        app: vault
    spec:
      serviceAccountName: app
      containers:
      - name: app
        image: alpine
        command: ["sleep", "9999999"]